### ISSUE TITLE
Gives Grass Block on Undo Instead of Dirt if Converted

### ISSUE THREAD

**Issue by ChosenArchitect** [Direwolf20-MC/BuildingGadgets2#45]
**Building Gadgets Version**
buildinggadgets2-1.0.5.jar

**Describe the bug**
When filled with dirt and that dirt turns into grass from the surrounding grass block. When you undo it will give the grass blocks instead of dirt.

**Expected behavior**
It to not silk touch the items it's giving back if changed but returns the original item placed.

Forge Version: Forge - Forge Version: 47.1.3

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
Grass is annoyingly a special case - most blocks i'm ok giving back the silk touched version of - like if you were building with redstone ore for some reason and accidently placed a row, I'm ok with the undo returning the silk touched ore. But grass..yea I can see your point :). But if you were building with grass, you'd want to undo and get your grass back, not dirt. 

I have to decide if I want to special case grass. The 'undo' method doesn't *really* track what block state was there before, mostly because it shouldn't matter. If you undo something, i wanna give you back whats really in that spot, not what you placed, so you can't place a diamond block, replace it with dirt manually, and then undo it and get a 2nd diamond block ;). 

This might just have to be one of those annoying quirks thats not easy to work around. I'll think on a good solution if there is one, but grass is just weird like that lol.
