### ISSUE TITLE
Copy-Paste Gadget refuses to copy AE2 cables

### ISSUE THREAD

**Issue by coaber** [Direwolf20-MC/BuildingGadgets2#95]
**Building Gadgets Version**
1.0.7

**Describe the bug**
For whatever reason, the copy paste gadget does not copy the AE2 cables at all, not even listing them inside the materials list, as if they are air blocks.

**To Reproduce**
Have a random AE2 setup with any configuration, any cables will not be copied over.

**Expected behavior**
For the whole selected area to have their respective counterparts copied over and listed inside the materials list.

**Screenshots**
![2024-05-17_13 28 43](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/26202628/f9221167-cf1b-4e2c-85d8-82a4e2ff94cd)
![2024-05-17_13 28 57](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/26202628/1f43b98c-8ad3-4c6c-aaf4-eda39597137f)
![image](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/26202628/9cfe9016-3ef1-4e83-aaa4-5301662aaf84)

**Log Files** 
Not exactly a crash related issue, but i will post latest and debug log below.

debug.log
https://gist.github.com/coaber/0b1a6aac6ae95c3f96116c2acf2093e7
latest.log
https://gist.github.com/coaber/9d503313fe0b2d1532c277ce1518aaba

**NOTE ON RUBIDIUM**
Running Embeddium 0.3.19 for reference to this note, unrelated to issue.

**Comment by Direwolf20-MC** [comment]
Unfortunately because AE2 cables are multiblocks - as in they can have a cable, export bus, and terminal all in one block space - they store this data on nbt. Copy paste gadget doesn’t support copying nbt - and it’s not easy to figure out what items are needed to place that multiblock. 

Someday I’d like to support stuff like this but it’s a far future addition ;)
